# Generated by Django 4.2.2 on 2023-06-09 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
