# Generated by Django 4.2.2 on 2023-06-08 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geojsonfile_services', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ErrorLogs',
        ),
    ]
