# Generated by Django 4.2.2 on 2023-06-08 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geojsonfile_services', '0002_delete_errorlogs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
