ERROR_CODES = {
    "DATA_VALIDATION_ERROR": "E400",
    "GEO_JSON_FILE_UPLOAD_ERROR": "E401",
    "GEO_JSON_FILE_INVALID_ID": "E402",
    "FEATURE_INVALID_ID": "E403",
    "UNKNOWN_ERROR": "E500"
}

SUCCESS_CODES = {
    "DEFAULT_SUCCESS_RESPONSE": "S200",
    "GEO_JSON_FILE_UPLOAD_SUCCESS": "S201",
    "GEO_JSON_FILE_LIST_SUCCESS": "S202",
    "GEO_JSON_FILE_RETRIEVE_SUCCESS": "S203",
    "GEO_JSON_FILE_DELETE_SUCCESS": "S204",
    "GEO_JSON_FILE_UPDATE_SUCCESS": "S205",
    "DATA_INSERT_SUCCESS": "S206",
    "FEATURE_LIST_SUCCESS": "S207",
    "FEATURE_RETRIEVE_SUCCESS": "S208",
    "FEATURE_UPDATE_SUCCESS": "S209",
    "FEATURE_DELETE_SUCCESS": "S210",
    "LOG_OUT_SUCCESS": "S211",
}

DEFAULT_SUCCESS_CODE = "S200"
DEFAULT_ERROR_CODE = "E500"
